env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Kernel-Build-Clang"
  timeout_in: 60m
  container:
      image: panchajanya1999/archlinux:latest
      cpu: 8
      memory: 32G

  build_script:
      - bash -c "$(curl https://raw.githubusercontent.com/z3zens/myscripts/master/kernel.sh)"
