name: Asyanx Build

on: [push]

jobs:
  kernel-build:
    runs-on: ubuntu-latest
    container:
      image: fedora:rawhide
    steps:
    - uses: actions/checkout@v2
    - name: Setup CI
      run: |
            dnf group install development-tools -y
            dnf install llvm lld bc bison ca-certificates curl flex glibc-devel.i686 glibc-devel binutils-devel openssl python3 python2 zstd clang gcc-arm-linux-gnu dtc libxml2 libarchive openssl-devel tomsfastmath-devel wget xz -y
            ln -sf "/usr/bin/python2" /usr/bin/python
    - name: Build Kernel
      run: bash kernel.sh
