name: z3zens Build

on: [push]

jobs:
  kernel-build:
    runs-on: buildjet-64vcpu-ubuntu-2204
    container:
      image: z3zens/ubuntu:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Kernel
      run: bash kernel.sh
