name: z3zens Build

on: [push]

jobs:
  kernel-build:
    runs-on: buildjet-64vcpu-ubuntu-2204
    container:
      image: panchajanya1999/archlinux:latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup CI
      run: |
        sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
        sudo pacman -Sy --noconfirm git bc inetutils python3 flex bison libc++ libxml2 python-pipx zip wget cpio jdk-openjdk tzdata && sudo pipx install networkx
    - name: Build Kernel
      run: bash kernel.sh
