name: Asyanx Build

on: [push]

jobs:
  kernel-build:
    runs-on: ubuntu-latest
    container:
      image: panchajanya1999/archlinux:latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup CI
      run: |
        sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
        sudo pacman -Sy --noconfirm git bc inetutils python3 flex bison curl libc++ libxml2 python-pipx zip wget cpio jdk-openjdk tzdata
#        curl -LO "https://launchpad.net/glibc/head/2.38/+download/glibc-2.38.tar.gz" && tar -C / -xvf "glibc-2.38.tar.gz"
    - name: Build Kernel
      run: bash kernel.sh
